### ISSUE TITLE
General issues

### ISSUE THREAD

**Issue by Stilic** [Arthurs-code/Funkin-Lua#3]
For now, the Sparrow atlas handler is very buggy.
This leave to some issues (checked items are fixed bugs):

- [ ] At start of the main menu state, the sprites are animating corretly. But after selecting, they start to have buggy offsets.
- [ ] `frame...` propreties are not supported for real yet.

**Comment by Stilic** [comment]
some cool links (or not idk??):
https://github.com/HTV04/funkin-rewritten/blob/69bef3cd3ec8f929fbd433ed713efd004ff620ba/src/love/modules/graphics.lua#L202

https://love2d.org/wiki/SpriteBatch

https://github.com/ninjamuffin99/Funkin/blob/master/assets/preload/images/gfDanceTitle.xml

https://github.com/stars/Stilic/lists/lua-lol

**Comment by Stilic** [comment]
@Arthurs-code What do you think of the fix I made?

**Comment by Arthurs-code** [comment]
what fi x

**Comment by Arthurs-code** [comment]
btw we should add discord rpc

**Comment by Arthurs-code** [comment]
https://github.com/pfirsich/lua-discordRPC

**Comment by Arthurs-code** [comment]
@Stilic

**Comment by Stilic** [comment]
> what fi x

i mean, the sprites still are buggy for you?

**Comment by Stilic** [comment]
> btw we should add discord rpc

yes, i will do that tommorow cuz i don't have access to my pc yet

**Comment by Stilic** [comment]
@Arthurs-code

**Comment by Arthurs-code** [comment]
> > what fi x
> 
> i mean, the sprites still are buggy for you?

yeah they kinda are

**Comment by Stilic** [comment]
> > > what fi x
> > 
> > 
> > i mean, the sprites still are buggy for you?
> 
> yeah they kinda are

Ok, I will see later

**Comment by Stilic** [comment]
hey kids, just remember: don't use tables with sprites or you will get a skill issue!
